---
- name: Crear directorio SSL y establecer permisos
  file:
    path: /etc/apache2/ssl
    state: directory
    mode: '0700'

- name: Copiar certificados SSL
  copy:
    src: "../.certs/{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop:
    - { src: '_.fondomarcador.com_private_key.key', dest: '/etc/apache2/ssl/private.key', mode: '0600' }
    - { src: 'fondomarcador.com_ssl_certificate.cer', dest: '/etc/apache2/ssl/certificate.crt', mode: '0644' }
    - { src: 'intermediate2.cer', dest: '/etc/apache2/ssl/intermediate.crt', mode: '0644' }
